config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :messages
  has_many :groups_users
  has_many :users, through: :groups_users
end

app/models/groups_user.rb
class GroupsUser < ApplicationRecord
  validates :group_id, :user_id, presence: true
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true, unless: :image_presence?
  belongs_to :user
  belongs_to :group
  mount_uploader :image, ImageUploader

  def image_presence?
    image.file.present?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :messages
  has_many :groups_users
  has_many :groups, through: :groups_users
  def print_name
    "#{name}"
  end

  def self.search(search)
    User.where('name LIKE(?)', "%#{search}%")
  end
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    group = Group.find(params[:group_id])
    last_message_id = params[:id].to_i
    @messages = group.messages.includes(:user).where("id > #{last_message_id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :move_to_sign_in
  
  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_name)
    if @group.save
      @group.update(group_users)
      flash[:notice] = "グループを作成しました"
      redirect_to root_path
    else
      render action: :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      flash[:notice] = "グループを編集しました"
      redirect_to "/groups/#{@group.id}/messages"
    else
      render action: :edit
    end
  end

  private
    def group_params
      params.require(:group).permit(:name, {user_ids: []})
    end

    def group_name
      params.require(:group).permit(:name)
    end

    def group_users
      params.require(:group).permit(user_ids: [])
    end

    def move_to_sign_in
      unless user_signed_in?
        flash[:alert] = "ログインまたは登録が必要です。"
        redirect_to new_user_session_path
      end
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :move_to_sign_in

  def index
    @groups = current_user.groups
    @group = Group.find(params[:group_id])
    @messages = @group.messages
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    respond_to do |format|
      if @message.save
        format.json
      else
        format.json { redirect_to group_messages_path }
      end
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :image).merge(user_id: current_user.id, group_id: params[:group_id])
  end

  def move_to_sign_in
    unless user_signed_in?
      flash[:alert] = "ログインまたは登録が必要です。"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_sign_in

  def index
    @users = User.search(params[:keyword])
    respond_to do |format|
      format.json
    end
  end

  def edit
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end

  def move_to_sign_in
    unless user_signed_in?
      flash[:alert] = "ログインまたは登録が必要です。"
      redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_error_messages.html.haml
.chat-group-form__errors
  %h2
    #{group.errors.full_messages.length}件のエラーが発生しました。
  %ul
    - group.errors.full_messages.each do |message|
      %li #{message}

app/views/groups/_form.html.haml
.chat-group-form__field
  .chat-group-form__field--left
    = f.label :name, "グループ名", class: "chat-group-form__label"
  .chat-group-form__field--right
    = f.text_field :name, placeholder: "グループ名を入力してください", class:"chat_group_name chat-group-form__input"

.chat-group-form__field
  .chat-group-form__field--left
    %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
  .chat-group-form__field--right
    .chat-group-form__search.clearfix
      %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
    #user-search-result

.chat-group-form__field.clearfix
  .chat-group-form__field--left
    %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
  .chat-group-form__field--right

    #chat-group-users.js-add-user
      .chat-group-user.clearfix.js-chat-member#chat-group-user-8
        %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
        %p.chat-group-user__name= current_user.name
      - group.users.each do |user|
        - if user.id != current_user.id
          .chat-group-user.clearfix.js-chat-member#chat-group-user-8
            %input{name: "group[user_ids][]", type: "hidden", value: user.id}
            %p.chat-group-user__name= user.name
            .user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除

.chat-group-form__field
  .chat-group-form__field--left
  .chat-group-form__field--right
    = f.submit "登録する", class: "chat-group-form__action-btn"

app/views/groups/_side_bar.html.haml
.chat-side
  .side-header
    .side-header__box
      %p.side-header__box__user-name #{current_user.name}
      %ul.side-header__box__menu
        %li.side-header__box__menu__new-group
          =link_to new_group_path do
            %i.fas.fa-edit
        %li.side-header__box__menu__edit-user
          =link_to "/users/#{current_user.id}/edit" do
            %i.fa.fa-cog
  .groups
    - groups.each do |group|
      =link_to "/groups/#{group.id}/messages" do
        .group
          %p.group__group-name #{group.name}
          %p.group__latest-message
            - if group.messages.present?
              - latest_message = group.messages.last
              - if latest_message.body.present?
                #{latest_message.body}
              - else
                画像が投稿されています
            - else
              まだメッセージはありません。

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  =form_for @group do |f| 
    = render "error_messages", group: @group if @group.errors.any?
    = render "form", f: f, group: @group

app/views/groups/index.html.haml
.wrapper
  = render "groups/side_bar", groups: @groups

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  =form_for @group do |f| 
    = render "error_messages", group: @group if @group.errors.any?
    = render "form", f: f, group: @group

app/views/layouts/_flash_messages.html.haml
.flash-box
  - flash.each do |key, value|
    = content_tag(:div, value, class: "flash-box__#{key}")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    -# = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    -# = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render "layouts/flash_messages"
    = yield

app/views/messages/_main_chat.html.haml
.chat-main
  .main-header
    .main-header__left-box
      %h2.main-header__left-box__current-group #{group.name}
      %ul.main-header__left-box__member-list
        %p Member :
        - group.users.each do |user|
          %li.main-header__left-box__member-list__member #{user.name}

    =link_to "/groups/#{group.id}/edit" do 
      .main-header__edit-btn
        Edit
  
  .messages
    - messages.each do |message|
      .message{data: {message_id: message.id} }
        .message__upper-info
          %p.message__upper-info__talker #{message.user.name}
          %p.message__upper-info__date #{message.created_at.to_s(:datetime)}
        %p.message__text #{message.body}
        %img(src="#{message.image.url}")

  .form
    =form_for [group, message] do |f|
      .input-box
        = f.text_field :body, placeholder: "type a message", class:"input-box__text"
        = f.label :image, class: "input-box__image far fa-image fa-2x" do
          = f.file_field :image, class:"input-box__image__file"
      = f.submit "Send", class: "submit-btn"

app/views/messages/index.html.haml
.wrapper
  = render "groups/side_bar", groups: @groups
  = render "main_chat", messages: @messages, message: @message, group: @group

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'